; ================================================================
;  platformio.ini
;
;  Se o seu board não for esp32dev, troque o valor de "board".
;  Lista completa: https://registry.platformio.org/platforms/espressif32/boards
;
;  Exemplos comuns:
;    esp32dev         → ESP32 DevKit v1 genérico
;    esp32-s3-devkitc-1 → ESP32-S3
;    az-delivery-devkit-v4
; ================================================================

[env:esp32-s3-devkitm-1]
platform      = espressif32
board         = esp32-s3-devkitm-1
framework     = arduino
monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=1          ; logs de debug do ESP32 no monitor serial

lib_deps =
    crankyoldgit/IRremoteESP8266
    https://github.com/mathieucarbou/AsyncTCP.git
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/JP-DEV-2302/Biblioteca-LED.git